CREATE DATABASE CAROUSER
USE CAROUSER
CREATE TABLE USERCARO
(
USERNAME CHAR(20)  NOT NULL PRIMARY KEY,
PASS CHAR(20) NOT NULL,
TENNGUOICHOI NVARCHAR(50),
SOLANCHOI INT DEFAULT(0),
SOLANTHANG INT DEFAULT(0)
)
drop TABLE USERCARO
insert into usercaro VALUES
('test1','1123456','Nguoi choi 1',10,10),
('test2','1123456','Nguoi choi 2',100,10),
('test3','1123456','Nguoi choi 3',10,0);

select * from usercaro
UPDATE USERCARO SET solanthang= solanthang+1 WHERE USERNAME= ''
select USERNAME from USERCARO where USERNAME='admin'